# Generated by Django 5.1.2 on 2024-12-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0002_location_place_placecomment_placerating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place_creator",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
