# Generated by Django 5.1.2 on 2024-12-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0003_place_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="user",
        ),
    ]
